### ISSUE TITLE
 Unable to install insightface, and manually install not work with this docker

### ISSUE THREAD

**Issue by NicoNicoNico123** [Yummiii/sd-webui-forge-docker#4]
Legacy Preprocessor init warning: Unable to install insightface automatically. Please try run `pip install insightface` manually,

Any solve of this issue?

**Comment by Yummiii** [comment]
Just pushed a build to try to fix this, you will need to delete your data folder and run with the new build (in docker compose just add the `--pull always` argument. You only need to do this once) and it should be fixed. Let me know if it worked :)

**Comment by NicoNicoNico123** [comment]
I solved it by add build-essential in dockerfile, but I faced another issue of install latest driver of nvidia, once I reverse back old driver, docker can run again, it's seem the torch issue

**Comment by Yummiii** [comment]
Can you specify where you added the build-essential, because in my tests I couldn't find a place where it made a difference. And for the drivers, I'll follow it in issue [1](https://github.com/Yummiii/sd-webui-forge-docker/issues/1)

**Comment by NicoNicoNico123** [comment]
> Can you specify where you added the build-essential, because in my tests I couldn't find a place where it made a difference. And for the drivers, I'll follow it in issue [1](https://github.com/Yummiii/sd-webui-forge-docker/issues/1)

```
FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04
LABEL org.opencontainers.image.source https://github.com/Yummiii/sd-webui-forge-docker
WORKDIR /app
RUN apt update && apt upgrade -y
RUN apt install -y wget git python3 python3-venv libgl1 libglib2.0-0 apt-transport-https libgoogle-perftools-dev bc build-essential python3-pip

COPY run.sh /app/run.sh
RUN chmod +x /app/run.sh

RUN useradd -m webui
RUN chown -R webui:webui /app
USER webui
RUN mkdir /app/sd-webui

ENTRYPOINT ["/app/run.sh"]
```

**Comment by Yummiii** [comment]
after testing this, adding the build-essential really didn't do anything. What probably happened was that you made the change after the [c64f5e6](https://github.com/Yummiii/sd-webui-forge-docker/commit/c64f5e6b8e92ac3091839a251a04ed255b5ef7e9) commit and it downloaded the latest image which had the fix
