### ISSUE TITLE
no support for cuda 12.2?

### ISSUE THREAD

**Issue by fahadshery** [Yummiii/sd-webui-forge-docker#6]
Hi,

I understand that the DockerFile is based on cuda 12.4 drivers. are you planning to support 12.2?

Cheers for this awesome project!

**Comment by Yummiii** [comment]
Hii, I currently don't see a reason to support the 12.2 drivers, however, if you really need them please let me know so that we can work something out!

**Comment by fahadshery** [comment]
Vast majority of my enterprise servers are running 12.2 drivers and it would be a massive pain to upgrade them just now. 
would appreciate it if we could build something that would support 12.2 for now. 
cheers

**Comment by Yummiii** [comment]
Released [this build](https://github.com/Yummiii/sd-webui-forge-docker/pkgs/container/sd-webui-forge-docker/273619509?tag=cuda12.2) that is using cuda 12.2 . Can you test it and see it if works for you ?

**Comment by fahadshery** [comment]
This works!!! Just built and tested juggernaut XL and everything went well...
can't thank you enough! I will do a bit more testing but for now, I am happy with the results!
Cheers mate
